services:
  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: whatsapp_admin
      MONGO_INITDB_ROOT_PASSWORD: secure_password_123
      MONGO_INITDB_DATABASE: whatsapp_sessions
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  app:
    build:
      context: .
      args:
        - SSH_KEY=${SSH_KEY}
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./session:/session  # Keep as backup
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data: